server:
  port: 9001

spring:
  application:
    name: server-payment
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sbcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin


#datasource:
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: org.gjt.mm.mysql.Driver
#  url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
#  username: root
#  password: 123456mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities
